export const ADD_FLY = 'ADD_FLY';
export const REMOVE_FLY = 'REMOVE_FLY';
export const SET_TOTAL_FLIES = 'SET_TOTAL_FLIES';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const START_GAME = 'START_GAME';
export const START_TIMER = 'START_TIMER';
export const PAUSE_TIMER = 'PAUSE_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const ILLEGAL_HUNT_OCCUR = 'ILLEGAL_HUNT_OCCUR';
export const ILLEGAL_HUNT_RESOLVED = 'ILLEGAL_HUNT_RESOLVED';
export const RESET_GAME = 'RESET GAME';
export const NO_FLIES_WARNING = 'NO_FLIES_WARNING';
export const NO_FLIES_WARNING_DEACTIVATE = 'NO_FLIES_WARNING_DEACTIVATE';
export const ADD_POINTS_POPOVER = 'ADD_POINTS_POPOVER';
export const REMOVE_POINTS_POPOVER = 'REMOVE_POINTS_POPOVER';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';


